version: "3.1"

services:
  application:
    image: application
    build:
      context: ./application
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - worker

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5673:5672

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq
