version: "3.1"

services:
  application:
    image: application
    build:
      context: ./application
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - worker

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: bitnami/rabbitmq:3.8.27
    ports:
      - 5673:5672

